/*
 * This source file was generated by the Gradle 'init' task
 */
import edu.princeton.cs.algs4.Draw;
package ifsc.poo;

public class App {
    private Draw draw;

    public App() {
        draw = new Draw();
        draw.setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);
        draw.setCanvasSize(1000, 600);
        draw.setXscale(0, 1000);
        draw.setYscale(0, 600);
    }

    public static void main(String[] args) {
        new App(); // Janela é exibida automaticamente
    }
}
