package ifsc.poo;/*
 * This source file was generated by the Gradle 'init' task
 */
import edu.princeton.cs.algs4.Draw;

public class App {
    // Atributos
    private Draw draw;

    // Construtor
    public App() {
        this.draw = new Draw();
        this.draw.setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);
        this.draw = new Draw();
        this.draw.setCanvasSize(1000, 600);
        this.draw.setXscale(0, 1000);
        this.draw.setYscale(0, 600);
       }

        // Main
        public static void main(String[] args){
        App app = new App();
        app.draw.show();
    }
}
